cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns =[
    path('',views.cart_detail,name='cart-detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart-add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart-remove')

]

gas_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls',namespace='cart')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('',include('shop.urls',namespace='shop')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
    

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/',views.order_create,name='order-create'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns =[
    path('',views.product_list,name='product-list'),
    path('<slug:category_slug>/',views.product_list,name='product-list-by-category'),
    path('<int:id>/<slug:slug>/',views.product_detail,name='product-detail'),
    
]

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models

class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30,default='100001')
    city = models.CharField(max_length=40)
    created= models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created']
        indexes = [
            models.Index(fields=['-created']),
            ]

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

    def __str__(self):
        return f'Order {self.id}'
    
class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name="items",
                              on_delete=models.CASCADE)
    product = models.ForeignKey('shop.Product',
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2
    )
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f'Order {self.id}'
    
    def get_cost(self):
        return self.price * self.quantity
    

shop/models.py
from django.db import models
from django.urls import reverse
from PIL import Image,ImageOps


class Category(models.Model):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=300,unique=True)

    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('shop:product-list-by-category',args=[self.slug])
    
    def __str__(self):
        return self.name
    
class Product(models.Model):
    name = models.CharField(max_length=300)
    category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='products')
    slug = models.SlugField(max_length=300)
    image = models.ImageField(upload_to=r'products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering= ['name']
        indexes = [models.Index(fields=['id','slug']),
                   models.Index(fields=['name']),
                   models.Index(fields=['-created'])]
        
    def get_absolute_url(self):
        return reverse('shop:product-detail',args=[self.id,self.slug])
    
    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        if self.image:
            target_width,target_height=300,300
            input_path = self.image.path
            output_path = self.image.path

            with Image.open(input_path) as img:
                img_resized = ImageOps.contain(img,size=(target_width,target_height))
                canvas = Image.new('RGB',(target_width,target_height),'white')
                offset_x = (target_width - img_resized.width) // 2
                offset_y = (target_height - img_resized.height) // 2
                canvas.paste(img_resized, (offset_x, offset_y))
                canvas.save(output_path, format="JPEG")
    
    def __str__(self):
        return self.name

    
    

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,31)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int
    )
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = [
            'first_name',
            'last_name',
            'email',
            'address',
            'postal_code',
            'city'
        ]

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request,product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,id=product_id)
    form=CartAddProductForm(request.POST)
    if form.is_valid():
        cd=form.cleaned_data
        cart.add(
            product=product,
            quantity=cd['quantity'],
            override_quantity=cd['override']
        )
    return redirect('cart:cart-detail')

@require_POST
def cart_remove(request,product_id):
    cart=Cart(request)
    product=get_object_or_404(Product,id=product_id)
    cart.remove(product)
    return redirect('cart:cart-detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'],'override':True})
    return render (request,'cart/cart_detail.html',{'cart':cart})

orders/views.py
from django.shortcuts import render
from cart.cart import Cart
from .forms import OrderCreateForm
from .models import OrderItem

def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(
                    order = order,
                    product = item['product'],
                    price = item['price'],
                    quantity = item['quantity']
                )
            cart.clear()
            return render(request,'orders/created.html',{'order':order})
    else:
        form = OrderCreateForm()
    return render(request,'orders/create.html',{'form':form,'cart':cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request,category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug = category_slug)
        products = products.filter(category = category)
    return render (request,'shop/product/product_list.html',{
        'category':category,
        'categories':categories,
        'products':products
    })

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id = id, slug=slug,available=True)
    category_name = product.category
    products = Product.objects.filter(category=category_name)
    cart_product_form = CartAddProductForm()

    return render(request,'shop/product/product_detail.html',{'product':product,'products':products,'cart_product_form':cart_product_form})

cart/templates/cart/cart_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Shopping Cart{% endblock %}

{% block content %}
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-bordered text-center mb-0">
                <thead class="bg-secondary text-dark">
                    <tr>
                        <th>Products</th>
                        <th>Unit Price</th>
                        <th>Quantity</th>
                        <th>Remove</th>
                        <th>Price</th>
                    </tr>
                </thead>

                <tbody class="align-middle">
                {% for item in cart %}
                    {% with product=item.product %}
                    <tr>
                        <td class="align-middle"><a href="{{product.get_absolute_url}}"><img src="{{product.image.url}}" alt="" style="width: 50px;"> {{product.name}}</a></td>
                        <td class="align-middle">{{item.price}}</td>
                        <td class="align-middle">
                            <form method="post" action="{% url 'cart:cart-add' product.id %}">
                                {{item.update_quantity_form.quantity}}
                                {{item.update_quantity_form.override}}
                                <input class="btn btn-primary" type="submit" value="Update">
                                {% csrf_token %}
                            </form>
                        </td>
                        <td class="align-middle">
                            <div class="input-group quantity mx-auto" style="width: 100px;">
                                <form action="{% url 'cart:cart-remove' product.id %}" method="post">
                                    {% csrf_token %}
                                    <input class="btn btn-primary" type="submit" value="Remove">
                                </form>
                            </div>
                        </td>
                        <td class="align-middle">{{ item.total_price }}</td>
                    </tr>
                    {% endwith %}
                {% endfor %}
                <tr class="align-items-start">
                    <td>Total</td>
                    <td colspan="3"></td>
                    <td class="align-middle">{{ cart.get_total_price }}</td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-5" action="">
                <div class="input-group">
                    <input type="text" class="form-control p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <div class="card border-secondary mb-5">
                <div class="card-header bg-secondary border-0">
                    <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between mb-3 pt-1">
                        <h6 class="font-weight-medium">Subtotal</h6>
                        <h6 class="font-weight-medium">NGN {{cart.get_total_price}}</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Logistics</h6>
                        <h6 class="font-weight-medium">Hello</h6>
                    </div>
                </div>
                <div class="card-footer border-secondary bg-transparent">
                    <div class="d-flex justify-content-between mt-2">
                        <h5 class="font-weight-bold">Total</h5>
                        <h5 class="font-weight-bold">{{cart.get_total_price}}</h5>
                    </div>
                    <button class="btn btn-block btn-primary my-3 py-3"><a href="{% url 'orders:order-create' %}">Proceed To Checkout</a></button>
                    <button class="btn btn-block bg-transparent my-3 py-3"><a href="{% url 'shop:product-list' %}">Continue Shopping</a></button>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

orders/templates/orders/create.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Checkout{% endblock %}

{% block content %}
<div class="row px-xl-5">
    <div class="col-lg-8">
        <div class="mb-4">
            <h4 class="font-weight-semi-bold mb-4">Shipping Details</h4>
            <form class="form-group" method="post">
                {{form|crispy}}
                <input class="btn btn-primary" value="Place Order" type="submit">
                {% csrf_token %}
            </form>
        </div>
    </div>
    <div class="col-lg-4">
        <div class="card border-secondary mb-5">
            <div class="card-header bg-secondary border-0">
                <h4 class="font-weight-semi-bold m-0">Order Total</h4>
            </div>
            <div class="card-body">
                <h5 class="font-weight-medium mb-3">Products</h5>
            {% for item in cart %}
                <div class="d-flex justify-content-between">
                    <p>{{item.quantity}} x {{item.product.name}}</p>
                    <p>{{item.total_price}}</p>
                </div>
            {% endfor %}
                <hr class="mt-0">
                <div class="d-flex justify-content-between mb-3 pt-1">
                    <h6 class="font-weight-medium">Subtotal</h6>
                    <h6 class="font-weight-medium">{{cart.get_total_price}}</h6>
                </div>
                <div class="d-flex justify-content-between">
                    <h6 class="font-weight-medium">Shipping</h6>
                    <h6 class="font-weight-medium">Free</h6>
                </div>
            </div>
            <div class="card-footer border-secondary bg-transparent">
                <div class="d-flex justify-content-between mt-2">
                    <h5 class="font-weight-bold">Total</h5>
                    <h5 class="font-weight-bold">{{cart.get_total_price}}</h5>
                </div>
            </div>
        </div>
        <div class="card border-secondary mb-5">
            <div class="card-header bg-secondary border-0">
                <h4 class="font-weight-semi-bold m-0">Payment</h4>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" name="payment" id="paypal">
                        <label class="custom-control-label" for="paypal">Paypal</label>
                    </div>
                </div>
                <div class="form-group">
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" name="payment" id="directcheck">
                        <label class="custom-control-label" for="directcheck">Direct Check</label>
                    </div>
                </div>
                <div class="">
                    <div class="custom-control custom-radio">
                        <input type="radio" class="custom-control-input" name="payment" id="banktransfer">
                        <label class="custom-control-label" for="banktransfer">Bank Transfer</label>
                    </div>
                </div>
            </div>
            <div class="card-footer border-secondary bg-transparent">
                <button class="btn btn-lg btn-block btn-primary font-weight-bold my-3 py-3">Place Order</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

orders/templates/orders/created.html
{% extends 'shop/base.html' %}
{% load static %}

{% block title %}Thank You{% endblock %}

{% block content%}
<div class="row">
    <div class="col-6">
        <p>Thank You for placing an order, Your Order ID is <strong>{{ order.id }}</strong></p>
    </div>

</div>

{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{% block title %}Gas Shop{% endblock %}</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'shop/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'shop/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid">
        <div class="row bg-secondary py-2 px-xl-5">
            <div class="col-lg-6 d-none d-lg-block">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark" href="">FAQs</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Help</a>
                    <span class="text-muted px-2">|</span>
                    <a class="text-dark" href="">Support</a>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-dark px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-dark pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
        <div class="row align-items-center py-3 px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a href="" class="text-decoration-none">
                    <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">Gas</span>Shop</h1>
                </a>
            </div>
            <div class="col-lg-6 col-6 text-left">
                <form action="">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search for products">
                        <div class="input-group-append">
                            <span class="input-group-text bg-transparent text-primary">
                                <i class="fa fa-search"></i>
                            </span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 col-6 text-right">
                <a href="" class="btn border">
                    <i class="fas fa-heart text-primary"></i>
                    <span class="badge">0</span>
                </a>
                <a href="{%url 'cart:cart-detail'%}" class="btn border">
                    <i class="fas fa-shopping-cart text-primary"></i>
                    <span class="badge">
                        {% with total_items=cart|length %}
                            {% if total_items > 0 %}
                                {{total_items}}
                            {% else %}
                                0
                            {% endif %}
                        {% endwith %}
                    </span>
                </a>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid">
        <div class="row border-top px-xl-5">
            <div class="col-lg-3 d-none d-lg-block">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-primary text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">{% block navbarname %}{% endblock %}</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                <nav class="collapse position-absolute navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0 bg-light" id="navbar-vertical" style="width: calc(100% - 30px); z-index: 1;">
                    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
                        {% block categories %}
                        {% endblock %}
                    </div>
                </nav>
            </div>
            <div class="col-lg-9">
                <nav class="navbar navbar-expand-lg bg-light navbar-light py-3 py-lg-0 px-0">
                    <a href="" class="text-decoration-none d-block d-lg-none">
                        <h1 class="m-0 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border px-3 mr-1">Gas</span>Shop</h1>
                    </a>
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
                        <div class="navbar-nav mr-auto py-0">
                            <a href="{% url 'shop:product-list' %}" class="nav-item nav-link">Home</a>
                            <a href="#" class="nav-item nav-link">Shop</a>
                            <a href="#" class="nav-item nav-link">Shop Detail</a>
                            <div class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pages</a>
                                <div class="dropdown-menu rounded-0 m-0">
                                    <a href="{% url 'cart:cart-detail' %}" class="dropdown-item">Shopping Cart</a>
                                    <a href="{% url 'orders:order-create' %}" class="dropdown-item">Checkout</a>
                                </div>
                            </div>
                            <a href="#" class="nav-item nav-link">Contact</a>
                        </div>
                        <div class="navbar-nav ml-auto py-0">
                            <a href="#" class="nav-item nav-link">Login</a>
                            <a href="#" class="nav-item nav-link">Register</a>
                        </div>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- Navbar End -->


    <!-- Shop Start -->
    <div class="container-fluid pt-5">
        {% block content %}
        {% endblock %}
    </div>
                
    <!-- Footer Start -->
    <div class="container-fluid bg-secondary text-dark mt-5 pt-5">
        <div class="row px-xl-5 pt-5">
            <div class="col-lg-4 col-md-12 mb-5 pr-3 pr-xl-5">
                <a href="" class="text-decoration-none">
                    <h1 class="mb-4 display-5 font-weight-semi-bold"><span class="text-primary font-weight-bold border border-white px-3 mr-1">Gas</span>Shopper</h1>
                </a>
                <p>Dolore erat dolor sit lorem vero amet. Sed sit lorem magna, ipsum no sit erat lorem et magna ipsum dolore amet erat.</p>
                <p class="mb-2"><i class="fa fa-map-marker-alt text-primary mr-3"></i>51 Madam Okesola</p>
                <p class="mb-2"><i class="fa fa-envelope text-primary mr-3"></i>danieligboke669@gmail.com</p>
                <p class="mb-0"><i class="fa fa-phone-alt text-primary mr-3"></i>+234 907 431 9031</p>
            </div>
            <div class="col-lg-8 col-md-12">
                <div class="row">
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Quick Links</h5>
                        <div class="d-flex flex-column justify-content-start">
                            <a class="text-dark mb-2" href="index.html"><i class="fa fa-angle-right mr-2"></i>Home</a>
                            <a class="text-dark mb-2" href="shop.html"><i class="fa fa-angle-right mr-2"></i>Our Shop</a>
                            <a class="text-dark mb-2" href="detail.html"><i class="fa fa-angle-right mr-2"></i>Shop Detail</a>
                            <a class="text-dark mb-2" href="cart.html"><i class="fa fa-angle-right mr-2"></i>Shopping Cart</a>
                            <a class="text-dark mb-2" href="checkout.html"><i class="fa fa-angle-right mr-2"></i>Checkout</a>
                            <a class="text-dark" href="contact.html"><i class="fa fa-angle-right mr-2"></i>Contact Us</a>
                        </div>
                    </div>
                    <div class="col-md-4">

                    </div>
                    <div class="col-md-4 mb-5">
                        <h5 class="font-weight-bold text-dark mb-4">Newsletter</h5>
                        <form action="">
                            <div class="form-group">
                                <input type="text" class="form-control border-0 py-4" placeholder="Your Name" required="required" />
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control border-0 py-4" placeholder="Your Email"
                                    required="required" />
                            </div>
                            <div>
                                <button class="btn btn-primary btn-block border-0 py-3" type="submit">Subscribe Now</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row border-top border-light mx-xl-5 py-4">
            <div class="col-md-6 px-xl-0">
                <p class="mb-md-0 text-center text-md-left text-dark">
                    &copy; <a class="text-dark font-weight-semi-bold" href="#">Gas Shop</a>. All Rights Reserved. Designed
                    by
                    <a class="text-dark font-weight-semi-bold" href="#">Igboke Daniel</a><br>
                    Distributed By <a href="#" target="_blank">Lordel</a>
                </p>
            </div>
            <div class="col-md-6 px-xl-0 text-center text-md-right">
                <img class="img-fluid" src="img/payments.png" alt="">
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-primary back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'shop/easing.min.js' %}"></script>
    <script src="{% static 'shop/owl.carousel.min.js' %}"></script>

    <!-- Contact Javascript File -->
    <script src="mail/jqBootstrapValidation.min.js"></script>
    <script src="mail/contact.js"></script>

    <!-- Template Javascript -->
    <script src="{% static 'shop/main.js' %}"></script>
</body>

</html>

shop/templates/shop/product/product_detail.html
{% extends 'shop/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbarname %}Products{% endblock %}
{% block categories %}
        <a href="{% url 'shop:product-list' %}" class="nav-item nav-link">All</a>
        {% for c in products %}
            <a href="{{c.get_absolute_url}}" class="nav-item nav-link">{{c.name}}</a>        
        {% endfor %}
                
{% endblock %}

{% block content %}
    <div class="text-center mb-4">
        <h1 class="section-title px-5"><span class="px-2">{{ product.name }}</span></h1>
        <h4 class="section-body" >{{product.category.name}}</h4>
    </div>
    <div class="row px-xl-5">
        <div class="col-lg-5 pb-5">
            <div>
                <img class="w-100 h-100" src="{{product.image.url}}" alt="Image">
            </div>
        </div>
        <div class="col-lg-7 px-5">
            <h3 class="section-body" >{{product.description}}</h3>
            <h6 class="text-muted">NGN {{product.price}}</h6>
            <form class="col-2" action="{% url 'cart:cart-add' product.id %}" method="post">
                {% csrf_token %}
                {{cart_product_form|crispy}}
                <input class="btn btn-primary" type="submit" value="Add to Cart">
            </form>
        </div>
    </div>
{% endblock %}